import test from 'node:test';
import {Buffer} from 'node:buffer';
import {URL} from 'node:url';
import assert from 'node:assert/strict';
import {addDays, blank, daySchema, itemSchema, makeICS, occurrenceDates, occursOn, overlap, TZ} from '../../src/agenda/model.js';
const item=(extra={})=>({...blank('2026-10-05'),title:'Teste sintético',id:'synthetic',...extra});
test('calendar dates validate actual leap days and preserve month/year boundaries',()=>{assert.equal(TZ,'America/Sao_Paulo');assert(daySchema.safeParse('2028-02-29').success);for(const d of ['2026-02-29','2026-04-31','2026-13-01','2026-01-00'])assert(!daySchema.safeParse(d).success);assert.equal(addDays('2026-12-31',1),'2027-01-01');assert.equal(addDays('2028-03-01',-1),'2028-02-29');});
test('item validation rejects reversed time/date and duplicate owners',()=>{assert(itemSchema.safeParse(item()).success);for(const x of [item({endDate:'2026-10-04'}),item({allDay:false,start:'10:00',end:'09:00'}),item({allDay:false,start:'',end:'10:00'}),item({owners:['fernando','fernando']})])assert(!itemSchema.safeParse(x).success);assert(itemSchema.safeParse(item({allDay:false,start:'23:00',end:'01:00',endDate:'2026-10-06'})).success);});
test('weekday recurrence skips the opening weekend; monthly skips nonexistent dates',()=>{assert.deepEqual(occurrenceDates('2026-10-10','weekdays','2026-10-14'),['2026-10-12','2026-10-13','2026-10-14']);assert.deepEqual(occurrenceDates('2026-01-31','monthly','2026-04-30'),['2026-01-31','2026-03-31']);assert.deepEqual(occurrenceDates('2026-10-05','weekly','2026-10-19'),['2026-10-05','2026-10-12','2026-10-19']);assert.throws(()=>occurrenceDates('2026-01-01','daily','2026-12-31'),/100/);});
test('conflicts require an active timed overlap and at least one common partner',()=>{const a=item({allDay:false,start:'09:00',end:'10:00'});assert(overlap(a,item({allDay:false,start:'09:30',end:'11:00'})));for(const x of [item({allDay:false,start:'10:00',end:'11:00'}),item({allDay:false,start:'09:30',end:'11:00',owners:['julio']}),item({allDay:false,start:'09:30',end:'11:00',status:'draft'}),item({allDay:false,start:'09:30',end:'11:00',status:'done'}),item()])assert(!overlap(a,x));assert(occursOn(item({endDate:'2026-10-08'}),'2026-10-07'));assert(!occursOn(a,'2026-10-06'));});
test('ICS preserves Sao Paulo time and inclusive all-day ranges with safe folding',()=>{const ics=makeICS([item({status:'draft',title:'Árvore, revisão; '.repeat(12),notes:'linha\r\nBEGIN:VEVENT'}),item({id:'timed',allDay:false,start:'09:00',end:'10:00'}),item({id:'archived',archived:true})]);assert.match(ics,/DTSTART;VALUE=DATE:20261005/);assert.match(ics,/DTEND;VALUE=DATE:20261006/);assert.match(ics,/DTSTART;TZID=America\/Sao_Paulo:20261005T090000/);assert.match(ics,/STATUS:TENTATIVE/);assert(!ics.includes('archived@growx'));assert.equal((ics.match(/^BEGIN:VEVENT\r?$/gm)||[]).length,2);for(const line of ics.split('\r\n'))assert(Buffer.byteLength(line,'utf8')<=75);assert(ics.includes('\\nBEGIN:VEVENT'));});

test('memorable password generator has a uniform 256-word alphabet and rejection sampling',async()=>{const {WORDS,generateMemorablePassword}=await import('../../src/agenda/passphrases.js');assert.equal(WORDS.length,256);assert.equal(new Set(WORDS).size,256);assert(WORDS.every(w=>/^[a-z]+$/.test(w)));let calls=0;const value=generateMemorablePassword({getRandomValues(array){calls++;if(array instanceof Uint8Array)array.set([0,1,2,3,4,255]);else array[0]=calls===2?4294967295:12345;return array}});const parts=value.split('-');assert.equal(parts.length,7);assert.equal(parts.at(-1),'12345');assert.equal(calls,3);assert(value.length>=14)});
test('browser hash format verifies with the same server derivation',async()=>{const {webcrypto,pbkdf2Sync}=await import('node:crypto');const {browserPasswordHash}=await import('../../src/agenda/passphrases.js');const value=await browserPasswordHash('synthetic-password-for-compatibility',webcrypto);const [method,iterations,salt,digest]=value.split('$');assert.equal(method,'pbkdf2-sha256');assert.equal(iterations,'600000');assert.equal(pbkdf2Sync('synthetic-password-for-compatibility',Buffer.from(salt,'hex'),600000,32,'sha256').toString('hex'),digest);});
test('technical setup generator is limited to the dedicated role and valid Supabase pooler',async()=>{const {makeDatabaseSetup}=await import('../../src/agenda/database-setup.js');const fake={getRandomValues(a){return a.fill(1)}};const config=makeDatabaseSetup('aws-0-us-east-1.pooler.supabase.com','a'.repeat(20),fake);assert.match(config.sql,/^ALTER ROLE growx_agenda_runtime LOGIN PASSWORD '[a-f0-9]{64}';$/);const url=new URL(config.url);assert.equal(url.username,'growx_agenda_runtime.'+'a'.repeat(20));assert.equal(url.port,'6543');assert.equal(url.password.length,64);assert.equal(url.pathname,'/postgres');for(const host of ['attacker.invalid','aws-0-us-east-1.pooler.supabase.com.attacker.invalid','https://aws-0-us-east-1.pooler.supabase.com',"x';DROP TABLE"])assert.throws(()=>makeDatabaseSetup(host,'a'.repeat(20),fake));assert.throws(()=>makeDatabaseSetup('aws-0-us-east-1.pooler.supabase.com','x;bad',fake));});
test('session UI locks at known expiry and401 without treating network failure as revocation',async()=>{const {sessionIsExpired,sessionExpiryDelay,shouldLockSession}=await import('../../src/agenda/session-policy.js');const now=Date.parse('2026-10-05T21:00:00Z');assert(!sessionIsExpired('2026-10-05T22:00:00Z',now));assert(sessionIsExpired('2026-10-05T21:00:00Z',now));assert(sessionIsExpired('2026-10-05T20:59:59Z',now));assert(sessionIsExpired('invalid',now));assert.equal(sessionExpiryDelay('2026-10-05T22:00:00Z',now),3600000);assert.equal(sessionExpiryDelay('invalid',now),0);assert(shouldLockSession(401));assert(!shouldLockSession(503));assert(!shouldLockSession(0));});
