import { Link } from 'react-router-dom';
import { buildInterestConsent } from '../../shared/interest-consent';
import { SEO, LeadForm } from '@/components/visual';
import { PageHero } from '@/components/sections';
import { Journey, JourneyCards } from '@/components/sections/MarketingJourney';

export default function ClosedPreSalePage() {
 return <><SEO title="Módulo Grow-X · pré-venda fechada" description="A pré-venda permanece fechada. Conheça a base documentada do módulo e avalie compatibilidade; nenhum pagamento ou reserva será solicitado." path="/prevenda"/>
 <PageHero eyebrow="Pré-venda fechada" title={<>Conheça o módulo. <span className="text-emerald-glow">Avalie seu projeto.</span></>} intro="O pagamento continua bloqueado. A abertura depende da validação do produto e da publicação das características essenciais, composição do kit, entrega e condições comerciais aprovadas." primaryCta={{label:'Receber aviso da abertura',href:'#lista'}} secondaryCta={{label:'Conversar sobre compatibilidade',href:'/contato?produto=modulo'}} imageFit="contain" image="/assets/module-render.webp" imageAlt="Render oficial conceitual do Módulo Grow-X" status="Nenhuma cobrança disponível" badge={<p className="text-sm text-muted-foreground">Render conceitual. Referência de varejo: R$ 5.000 por unidade. Não constitui oferta de compra, reserva ou promessa de entrega.</p>}/>
 <Journey id="modulo" eyebrow="Base documentada" title="Seis saídas AC, DHT22 e sensores compatíveis." intro="Composição e instalação precisam ser definidas no projeto. A demonstração web do GXP é informativa; comandos físicos continuam em validação."><JourneyCards items={[{title:'Especificações essenciais',text:'Tensão, corrente, carga máxima, dimensões e compatibilidade deverão estar confirmadas antes de qualquer pagamento.'},{title:'Kit e entrega',text:'Equipamentos incluídos, acessórios externos e custo total da entrega deverão constar da proposta aprovada.'},{title:'Condições comerciais',text:'Abertura, pagamento e prazos dependem de aprovação específica. Nenhuma data de entrega ou bônus está prometido nesta página.'}]}/></Journey>
 <Journey id="lista" eyebrow="Aviso de abertura" title="Receba o aviso, sem reservar uma unidade." intro="Este cadastro não inicia cobrança nem garante preço, bônus ou entrega. Os avisos ficam limitados à pré-venda e ao lançamento do módulo."><div className="max-w-xl"><LeadForm form="prevenda-lista" segment="cultivo" source="prevenda" enrich={false} extra={{consent:buildInterestConsent(),message:'Interesse na abertura do Módulo Grow-X.'}} fields={[{name:'name',label:'Nome',required:true},{name:'email',label:'E-mail para o aviso',type:'email',required:true},{name:'phone',label:'WhatsApp (opcional)',type:'tel'},{name:'agree',label:'Autorizo avisos da pré-venda e do lançamento por e-mail e, se informado, WhatsApp. Sem outras campanhas.',type:'checkbox',required:true}]} submitLabel="Receber aviso da abertura" successTitle="Interesse recebido pelo canal." successText="O cadastro não abre uma reserva nem inicia cobrança."/></div></Journey>
 <Journey id="reservar" eyebrow="Pedidos anteriores" title="Já possui um pedido?" intro="Os canais de consulta de pedidos anteriores permanecem disponíveis."><Link to="/prevenda/pedido" className="btn-ghost">Consultar pedido anterior</Link></Journey></>;
}
