import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, ChevronDown, Lightbulb, Droplets, Wind, Thermometer, Smartphone, PlugZap } from 'lucide-react';
import { SEO, LeadForm } from '@/components/visual';
import ThemeToggle from '@/components/visual/ThemeToggle';
import { track } from '@/lib/analytics';
import { whatsappLink } from '@/lib/crm';
import { buildInterestConsent } from '../../shared/interest-consent';
import logo from '../assets/logo-growx-oficial.png';
import './PreSaleExperience.css';

const compatibility = whatsappLink('Olá! Quero avaliar a compatibilidade do Módulo Grow-X com os equipamentos do meu projeto.');
const screens = [
  { id: 'jardim', label: 'Jardim', src: '/assets/prevenda-gxp/jardim.jpg', title: 'Encontre cada cultivo no seu contexto.', text: 'Ambientes e plantas organizados para retomar o percurso sem procurar em conversas e arquivos separados.' },
  { id: 'diario', label: 'Diário', src: '/assets/prevenda-gxp/diario.jpg', title: 'O que mudou fica registrado.', text: 'Fotos, notas e o percurso do cultivo no mesmo lugar. Consulte suas observações para acompanhar o que aconteceu.' },
  { id: 'modulo', label: 'Módulo', src: '/assets/prevenda-gxp/modulo.jpg', title: 'O equipamento também tem seu lugar.', text: 'A área Módulo contextualiza o equipamento no GXP. Nesta versão, a tela é informativa: não envia comandos físicos.' },
];
const scenarios = [
  { icon: Lightbulb, title: 'Luz', pain: 'Horários espalhados em temporizadores.', control: 'Centralizar o liga/desliga de iluminação compatível.', benefit: 'Uma rotina para consultar e ajustar.', detail: 'Controle projetado. Dimming depende de driver compatível e validação específica.' },
  { icon: Droplets, title: 'Rega', pain: 'Bomba e leituras de solo sem contexto.', control: 'Relacionar sensores compatíveis à atuação da bomba.', benefit: 'Regras e limites definidos para o seu projeto.', detail: 'Sensor, bomba e rotina de rega precisam de compatibilidade e homologação.' },
  { icon: Thermometer, title: 'Clima', pain: 'Leituras que você precisa conferir uma a uma.', control: 'Reunir temperatura e umidade do ar na proposta de monitoramento.', benefit: 'Mais contexto para avaliar o ambiente.', detail: 'DHT22 é a referência documentada; inclusão no kit ainda precisa de confirmação.' },
  { icon: Wind, title: 'Ventilação', pain: 'Exaustor e ventilador com ajustes separados.', control: 'Integrar equipamentos compatíveis às saídas AC.', benefit: 'Menos controles isolados na sua rotina.', detail: 'Tensão, corrente e carga de cada equipamento precisam ser verificadas.' },
];
const questions = [
  ['Posso usar com o grow que já tenho?', 'A proposta é integrar equipamentos compatíveis ao seu setup. Antes de contratar, o time precisa conferir tensão, corrente, potência e características de cada carga, além de sensores e instalação. Ter uma tomada compatível fisicamente não comprova compatibilidade elétrica.'],
  ['O GXP e o Módulo são o mesmo produto?', 'Não. O GXP é o software para organizar ambientes, plantas e registros. O Módulo é o hardware projetado para conectar equipamentos compatíveis à automação. Acesso ao app, plano e eventual benefício incluído no kit serão definidos na proposta comercial.'],
  ['O que vem no kit?', 'A base documentada do controlador prevê seis saídas AC e DHT22 como referência de temperatura e umidade do ar. A lista final de itens, quantidades, sensores, cabos e acessórios ainda será confirmada. Não considere lâmpadas, bombas, ventiladores ou um kit de cultivo incluídos.'],
  ['As telas mostram um equipamento funcionando?', 'As capturas são do GXP real em uma conta de QA, registradas em 09/10/2026. Elas mostram o software, não um teste físico do controlador. Firmware integrado, comandos, push e claim do dispositivo continuam em homologação. Os renders do hardware são conceituais.'],
  ['Qual é o preço e quando posso comprar?', 'A referência de varejo atualmente publicada é R$ 5.000 por unidade. Ela não constitui oferta de compra. Preço final de pré-venda, condições, kit, entrega e frete precisam de aprovação antes da abertura. Nenhum pagamento ou reserva está disponível agora.'],
  ['Como serão instalação e suporte?', 'Manual final, limites elétricos, orientação de instalação e escopo de suporte precisam constar da proposta aprovada. Na conversa de compatibilidade, informe os equipamentos que deseja conectar; o time poderá avaliar o cenário antes de qualquer contratação.'],
];
const event = (name, details = {}) => track(name, { page: '/prevenda', ...details });

function InterestCta({ placement, children = 'Receber aviso da abertura' }) {
  return <a className="ps-primary" href="#lista" onClick={() => event('click_cta_prevenda', { placement, intent: 'interest' })}>{children}<ArrowRight size={18} aria-hidden="true" /></a>;
}

export default function ClosedPreSalePage() {
  const [activeScreen, setActiveScreen] = useState(1);
  const screen = screens[activeScreen];
  return <div className="ps-experience">
    <SEO title="GXP + Módulo Grow-X — seu cultivo, conectado" description="Conheça o GXP real e o Módulo Grow-X projetado com seis saídas AC. Avalie compatibilidade e receba o aviso de abertura; pré-venda fechada, sem cobrança ou reserva." path="/prevenda" />
    <header className="ps-header"><div className="ps-wrap ps-header-row">
      <Link to="/" aria-label="Grow-X, página inicial"><img src={logo} width="150" height="40" alt="Grow-X" /></Link>
      <nav aria-label="Nesta página"><a href="#gxp">GXP em uso</a><a href="#compatibilidade">Seu setup</a><a href="#duvidas">Dúvidas</a></nav>
      <div className="ps-header-actions"><ThemeToggle /><InterestCta placement="header" /></div>
    </div></header>

    <section className="ps-hero ps-wrap" aria-labelledby="ps-title">
      <div className="ps-hero-copy"><p className="ps-eyebrow">GXP + Módulo Grow-X</p>
        <h1 id="ps-title">Seu cultivo.<br />Uma visão completa.<br /><span>Uma rotina conectada.</span></h1>
        <p className="ps-intro">O GXP organiza a história do seu cultivo. O Módulo é o próximo passo: conectar luz, rega, clima e ventilação compatíveis em uma central com seis saídas AC.</p>
        <div className="ps-actions"><InterestCta placement="hero" /><a className="ps-text-link" href={compatibility} target="_blank" rel="noopener noreferrer" onClick={() => event('click_whatsapp', { intent: 'compatibility', placement: 'hero' })}>Avaliar meu setup <ArrowRight size={16} aria-hidden="true" /></a></div>
        <p className="ps-status"><span aria-hidden="true" />Pré-venda fechada. Cadastro de interesse, sem cobrança ou reserva.</p><p className="ps-reference">Referência de varejo: R$ 5.000/unidade. Preço final de pré-venda ainda não aprovado.</p>
      </div>
      <figure className="ps-hero-product"><img src="/assets/module-render.webp" width="1600" height="900" fetchPriority="high" alt="Render conceitual do Módulo Grow-X com seis saídas AC" /><figcaption>Render conceitual do produto. Hardware e integração física em homologação.</figcaption><div className="ps-product-label"><span>Módulo Grow-X</span><strong>6 saídas AC</strong><small>Base documentada do controlador</small></div></figure>
    </section>

    <section className="ps-pair-band"><div className="ps-wrap ps-pair"><div><Smartphone aria-hidden="true" /><p><strong>GXP: organizar e acompanhar</strong><span>Software com Jardim, Diário e contexto do equipamento.</span></p></div><span className="ps-plus" aria-hidden="true">+</span><div><PlugZap aria-hidden="true" /><p><strong>Módulo: conectar e atuar</strong><span>Hardware projetado para equipamentos compatíveis.</span></p></div></div></section>

    <section className="ps-context ps-light" aria-labelledby="ps-context-title"><div className="ps-wrap"><div className="ps-context-heading"><p className="ps-eyebrow">Dentro do seu espaço</p><h2 id="ps-context-title">A rotina acontece aqui.<br />O contexto acompanha você.</h2><p>Da tenda ao registro no GXP, cada equipamento e cada observação fazem parte do mesmo projeto.</p></div><figure><img src="/assets/gxp-garden.webp" width="1536" height="1024" loading="lazy" alt="Cena ilustrativa de uma pessoa consultando o Jardim do GXP ao lado de uma tenda indoor iluminada" /><figcaption>Cena ilustrativa gerada por IA, já publicada no site. Interface real com dados de demonstração. Tenda, iluminação e acessórios não presumidos no kit; a cena não comprova uma instalação validada.</figcaption></figure></div></section>

    <section id="gxp" className="ps-wrap ps-section" aria-labelledby="ps-gxp-title">
      <div className="ps-section-heading"><p className="ps-eyebrow">Comece pelo que você consegue ver</p><h2 id="ps-gxp-title">Seu cultivo já tem história.<br />Dê um lugar a ela.</h2><p>Antes de automatizar equipamentos, reúna o contexto. Estas são capturas originais do GXP em uso, sem recriar a interface.</p></div>
      <div className="ps-demo"><div className="ps-demo-copy"><div className="ps-screen-buttons" aria-label="Escolher tela do GXP">{screens.map((item, index) => <button key={item.id} type="button" aria-pressed={activeScreen === index} onClick={() => { setActiveScreen(index); event('prevenda_demo_view', { screen: item.id }); }}>{item.label}</button>)}</div><p className="ps-eyebrow">GXP real · {screen.label}</p><h3>{screen.title}</h3><p>{screen.text}</p><div className="ps-evidence"><Check size={18} aria-hidden="true" /><p>Captura original · conta de QA · 09/10/2026.<br />Demonstração do software, sem prova de acionamento físico.</p></div><Link className="ps-text-link" to="/solucoes/growx-app" onClick={() => event('prevenda_app_explore')}>Conhecer o GXP <ArrowRight size={16} aria-hidden="true" /></Link></div><figure className="ps-screen"><img key={screen.id} src={screen.src} width="780" height="1560" loading="lazy" alt={`Captura original do GXP, tela ${screen.label}, conta de QA`} /><figcaption>{screen.id === 'modulo' ? 'Tela informativa. Esta versão não envia comandos.' : 'Interface real, com dados da conta de QA.'}</figcaption></figure></div>
    </section>

    <section className="ps-scenarios"><div className="ps-wrap ps-section"><div className="ps-section-heading"><p className="ps-eyebrow">Do controle espalhado à rotina conectada</p><h2>O que o Módulo foi<br />projetado para reunir.</h2><p>Cada equipamento tem uma função. A proposta é dar a eles um ponto de controle comum, respeitando a compatibilidade do seu projeto.</p></div><div className="ps-scenario-grid">{scenarios.map(({ icon: Icon, ...item }) => <article key={item.title}><Icon size={25} strokeWidth={1.5} aria-hidden="true" /><h3>{item.title}</h3><p className="ps-pain">{item.pain}</p><p>{item.control}</p><strong>{item.benefit}</strong><small>{item.detail}</small></article>)}</div><p className="ps-footnote">Capacidades projetadas. Firmware, comandos físicos, notificações push e vinculação do dispositivo ainda precisam de homologação. Nenhum teste físico é apresentado nesta página.</p></div></section>

    <section id="compatibilidade" className="ps-section ps-light"><div className="ps-wrap ps-kit"><div><p className="ps-eyebrow">Para quem já tem um setup</p><h2>Aproveitar o que faz sentido.<br /><span>Conferir antes de conectar.</span></h2><p>O Módulo é uma central de controle. Ele não substitui a lâmpada, a bomba ou o exaustor. A proposta final deve separar o controlador, os acessórios e os equipamentos que você já possui.</p><figure className="ps-system-diagram"><p className="ps-eyebrow">Relação projetada</p><div className="ps-diagram-node"><Smartphone aria-hidden="true" /><div><strong>GXP</strong><span>Ambientes · registros · contexto</span></div></div><div className="ps-connector"><span>Integração em homologação</span></div><div className="ps-diagram-node"><PlugZap aria-hidden="true" /><div><strong>Módulo Grow-X</strong><span>6 saídas AC documentadas</span></div></div><div className="ps-connector"><span>Equipamentos compatíveis</span></div><div className="ps-diagram-outputs">{scenarios.map(({ icon: Icon, title }) => <div key={title}><Icon size={19} aria-hidden="true" /><span>{title}</span></div>)}</div><figcaption>Esquema explicativo de capacidade projetada. Não é diagrama elétrico, lista de itens incluídos ou prova de acionamento físico.</figcaption></figure></div><div className="ps-checklist"><h3>O que precisa ficar claro na sua proposta</h3><dl><div><dt>Controlador</dt><dd>Seis saídas AC documentadas. Tensões, correntes, carga máxima e dimensões finais a confirmar.</dd></div><div><dt>Sensores e acessórios</dt><dd>DHT22 como referência de temperatura e umidade do ar. Modelos, quantidades, cabos e inclusão no kit ainda em definição.</dd></div><div><dt>Equipamentos do seu grow</dt><dd>Iluminação, bombas e ventilação precisam de avaliação elétrica e funcional. Não são itens incluídos confirmados.</dd></div><div><dt>GXP e suporte</dt><dd>Acesso ao app, plano, eventual benefício, instalação e suporte serão definidos nas condições finais.</dd></div></dl><a className="ps-text-link" href={compatibility} target="_blank" rel="noopener noreferrer" onClick={() => event('click_whatsapp', { intent: 'compatibility', placement: 'kit' })}>Conferir meus equipamentos com o time <ArrowRight size={16} aria-hidden="true" /></a></div></div></section>

    <section id="duvidas" className="ps-faq ps-wrap ps-section"><div className="ps-section-heading"><p className="ps-eyebrow">Decidir com clareza</p><h2>As perguntas que vêm<br />antes da compra.</h2></div><div>{questions.map(([question, answer]) => <details key={question} onToggle={(e) => { if (e.currentTarget.open) event('prevenda_faq_open', { question }); }}><summary>{question}<ChevronDown size={20} aria-hidden="true" /></summary><p>{answer}</p></details>)}</div></section>

    <section id="lista" className="ps-interest ps-light"><div className="ps-wrap ps-section ps-interest-grid"><div><p className="ps-eyebrow">Seu próximo passo</p><h2>Conheça a oferta<br />quando estiver pronta<br /><span>para ser decidida.</span></h2><p>Receba o aviso de abertura com kit, preço e condições finais. Se você já tem equipamentos, pode começar pela conversa de compatibilidade.</p><div className="ps-commercial"><strong>Pré-venda fechada</strong><p>Referência de varejo já publicada: <b>R$ 5.000 por unidade.</b> Não constitui oferta de compra nem promessa de entrega.</p><p>Preço de pré-venda, pagamento, prazo, frete e composição do kit ainda precisam de aprovação. Nenhum pagamento ou reserva está disponível.</p></div><a className="ps-text-link" href={compatibility} target="_blank" rel="noopener noreferrer" onClick={() => event('click_whatsapp', { intent: 'compatibility', placement: 'interest' })}>Prefiro conversar sobre meu setup <ArrowRight size={16} aria-hidden="true" /></a></div><div className="ps-form-panel"><h3>Receber aviso da abertura</h3><p>Sem pagamento. Sem reserva de unidade.</p><LeadForm form="prevenda-lista" segment="cultivo" source="prevenda" enrich={false} extra={{ consent: buildInterestConsent(), message: 'Interesse na abertura do Módulo Grow-X.' }} fields={[{ name: 'name', label: 'Nome', required: true }, { name: 'email', label: 'E-mail para o aviso', type: 'email', required: true }, { name: 'phone', label: 'WhatsApp (opcional)', type: 'tel' }, { name: 'agree', label: 'Autorizo avisos da pré-venda e do lançamento por e-mail e, se informado, WhatsApp. Sem outras campanhas.', type: 'checkbox', required: true }]} submitLabel="Receber aviso da abertura" successTitle="Solicitação aceita pelo canal de contato." successText="O canal confirmou o recebimento da solicitação. Isso não confirma entrega do aviso, reserva ou compra." onSuccess={(res) => event('prevenda_interest_accepted', { channel: res.mode })} /><p className="ps-privacy">Seus dados são usados para este contato, conforme a <Link to="/privacidade">Política de Privacidade</Link>. Nenhum CPF, endereço ou dado de pagamento é solicitado.</p></div></div></section>

    <footer className="ps-wrap ps-footer"><Link to="/" aria-label="Página inicial Grow-X"><img src={logo} width="130" height="35" alt="Grow-X" /></Link><p>GXP + Módulo Grow-X<br /><span>Tecnologia para o contexto do seu cultivo.</span></p><div><Link to="/prevenda/pedido">Consultar pedido anterior</Link><Link to="/privacidade">Privacidade</Link><a href={compatibility} target="_blank" rel="noopener noreferrer" onClick={() => event('click_whatsapp', { intent: 'support', placement: 'footer' })}>WhatsApp +55 41 99549-4343</a></div></footer>
    <aside className="ps-sticky" aria-label="Cadastro de interesse"><span>GXP + Módulo <small>Sem cobrança ou reserva</small></span><InterestCta placement="sticky" children="Quero acompanhar" /></aside>
  </div>;
}
