import CatalogEditorial from '@/components/sections/CatalogEditorial';
import InstitutionalVideo from '@/components/sections/InstitutionalVideo';
import { SEO, softwareSchema } from '@/components/visual';
import { PageHero } from '@/components/sections';
import { Journey, JourneyCards, ProductScene, GxpPrices } from '@/components/sections/MarketingJourney';
import { APP_PORTAL_URLS } from '@/lib/portalLinks';

export default function GrowXAppPage() {
 return <><SEO title="GXP · Jardim, Diário e sua experiência" description="Seu espaço, seus registros e sua história. Conheça Jardim, Diário, informações dos equipamentos e opções de acesso ao GXP." path="/solucoes/growx-app" jsonLd={softwareSchema({name:'GXP',description:'Organização de ambientes, registros e contexto de equipamentos.',applicationCategory:'LifestyleApplication',os:'Web'})}/>
 <PageHero eyebrow="GXP · Experiência e registro" title={<>Seu espaço. Seus registros. <span className="text-emerald-glow">Sua história.</span></>} intro="O que mudou hoje? Reúna observações, fotos e contexto para consultar sua própria experiência no tempo." primaryCta={{label:'Conhecer as telas do GXP',href:'#experiencia-gxp'}} secondaryCta={{label:'Abrir portal GXP',href:APP_PORTAL_URLS.gxp,external:true}} imageFit="contain" image="/assets/gxp-diary.webp" imageAlt="Cena ilustrativa gerada por IA: Diário do GXP em interface real com dados de demonstração" status="Experiência web demonstrada" badge={<p className="text-sm text-muted-foreground">Cena ilustrativa gerada por IA; interface real com dados de demonstração. Comandos físicos e composição do módulo continuam em validação.</p>}/>
 <Journey id="experiencia-gxp" eyebrow="Diário" title="O que você viu merece contexto."><ProductScene src="/assets/gxp-diary.webp" alt="Pessoa consulta um registro do Diário do GXP em cena ilustrativa" title="Fotos, notas e memória." text="O Diário ajuda a guardar o que você observou. Registre para retomar depois; uma anotação no app não é uma garantia de resultado agronômico ou clínico."/></Journey>
 <Journey eyebrow="Jardim" title="Cada registro tem seu lugar."><ProductScene src="/assets/gxp-garden.webp" alt="Jardim do GXP exibido em um telefone em cena ilustrativa" title="Encontre o contexto antes de abrir o Diário." text="Organize ambientes e registros no mesmo percurso. Busque o espaço pelo nome e retome o que deseja consultar."/></Journey>
 <Journey eyebrow="Equipamentos" title="O módulo também tem contexto no app."><ProductScene src="/assets/gxp-device.webp" alt="Área Módulo do GXP em cena ilustrativa" title="Consultar com clareza." text="A tela demonstrada reúne cadastro e informações de equipamentos. O acompanhamento demonstrado é informativo; sensores, acessórios, instalação e comandos físicos dependem de compatibilidade e validação do projeto."/></Journey>
 <Journey eyebrow="Perfil e participação" title="Guardar e compartilhar são escolhas diferentes."><ProductScene src="/assets/gxp-privacy.webp" alt="Preferências de perfil do GXP em cena ilustrativa" title="Você escolhe o que compartilha." text="Consulte as preferências do perfil e as permissões de seu acesso antes de compartilhar registros. Participar do Clube e registrar no Diário são ações distintas."/></Journey>
 <InstitutionalVideo videoId="9TTyJt6RfVA" sectionId="video-gxp" copy={{PT:{eyebrow:'Apresentação GXP',title:'Conheça o GXP e o módulo.',description:'Apresentação existente. Recursos e condições atuais dependem da validação e da proposta.',videoTitle:'Apresentação do GXP e Módulo Grow-X'},EN:{eyebrow:'GXP presentation',title:'Meet GXP and the module.',description:'Existing presentation. Current features and conditions depend on validation and the proposal.',videoTitle:'GXP and Grow-X Module presentation'}}} portrait/>
 <GxpPrices/>
 <CatalogEditorial universe/>
 <Journey eyebrow="Próxima conversa" title="Um projeto que faça sentido para você."><JourneyCards items={[{title:'Seu acesso ao GXP',text:'Confira os recursos, permissões e condições de seu acesso no portal.',href:APP_PORTAL_URLS.gxp,label:'Abrir portal GXP'},{title:'Compatibilidade do módulo',text:'Avalie equipamentos e sensores antes de qualquer contratação.',to:'/produtos/modulo-sem-fio',label:'Conhecer o módulo'},{title:'Sua dúvida',text:'Converse sobre acesso, demonstração ou o escopo de seu projeto.',to:'/contato?produto=gxp',label:'Conversar sobre o GXP'}]}/></Journey></>;
}
