import { ArrowUpRight, ArrowDown } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SEO, Container, Eyebrow } from '@/components/visual';
import GreenVeilSection from '@/components/sections/GreenVeilSection';
import './InstitutionalHome.css';

const sectors = [
  { id: 'agricultura', number: '01', name: 'Agricultura', product: 'SPP · Supply-X', headline: 'O campo tem história. O registro dá continuidade.', intro: 'Áreas, atividades e documentos no contexto de quem produz. Agricultura familiar, produção orgânica, cooperativas e acompanhamento técnico têm seus próprios caminhos.', image: '/assets/institutional/agriculture-scene-1200.webp', mobile: '/assets/institutional/agriculture-scene-480.webp', alt: 'Cena ilustrativa do acervo: produtora acompanha plantas em uma área agrícola', screen: '/assets/institutional/spp-screen-1600.webp', screenMobile: '/assets/institutional/spp-screen-800.webp', screenAlt: 'Tela demonstrada do SPP com parâmetros e cálculo de irrigação', proof: 'Do trabalho na área ao histórico da operação.', detail: 'Conheça as telas demonstradas e os percursos de registro para o produtor. Integrações, implantação e acompanhamento são definidos na proposta.', href: 'https://www.supplyx.com.br/spp', label: 'Explorar Agricultura e SPP' },
  { id: 'industria', number: '02', name: 'Indústria', product: 'SPI · Supply-X', headline: 'Cada operação tem seu ritmo. E seus responsáveis.', intro: 'Remessas, qualidade, armazenagem e contexto da operação. Da estrutura pequena à indústria de maior escala, o escopo acompanha as necessidades do projeto.', image: '/assets/institutional/industry-scene-1200.webp', mobile: '/assets/institutional/industry-scene-480.webp', alt: 'Cena ilustrativa do acervo: profissionais avaliam registros e qualidade em ambiente industrial', screen: '/assets/institutional/spi-screen-1600.webp', screenMobile: '/assets/institutional/spi-screen-800.webp', screenAlt: 'Tela demonstrada do SPI com lista e status de remessas', proof: 'Informação para retomar a operação com contexto.', detail: 'Veja a apresentação do SPI, os fluxos demonstrados e as opções por porte de operação. Recursos e integrações são avaliados e contratados por projeto.', href: 'https://www.supplyx.com.br/spi', label: 'Explorar Indústria e SPI' },
  { id: 'indoor', number: '03', name: 'Plantio Indoor', product: 'GXP + Módulo Grow-X', headline: 'Seu espaço. Seus registros. Sua experiência.', intro: 'Jardim, Diário e contexto dos equipamentos no GXP. O Módulo Grow-X entra na conversa conforme as necessidades e a compatibilidade do seu espaço.', image: '/assets/gxp-context.webp', alt: 'Cena ilustrativa gerada por IA: pessoa consulta o GXP em seu espaço de cultivo', screen: '/assets/module-render.webp', screenAlt: 'Render conceitual do Módulo Grow-X no acervo oficial da marca', proof: 'O aplicativo e o equipamento têm papéis próprios.', detail: 'Módulo documentado com seis saídas AC, DHT22 e sensores compatíveis. Composição, instalação e comandos físicos seguem em validação; pré-venda fechada.', to: '/solucoes/growx-app', label: 'Explorar GXP e Indoor' },
];

function SectorLink({ sector, className = '' }) {
  const content = <>{sector.label}<ArrowUpRight size={18} aria-hidden="true" /></>;
  return sector.to ? <Link className={className} to={sector.to}>{content}</Link> : <a className={className} href={sector.href}>{content}</a>;
}

export default function HomePage() {
  return <><SEO title="Grow-X Co. — Agricultura, Indústria e Plantio Indoor" description="Conheça os três núcleos da Grow-X Co.: Agricultura com SPP, Indústria com SPI e Plantio Indoor com GXP e Módulo Grow-X. Cada projeto começa no seu contexto." path="/" />
    <div className="institutional-home">
      <section className="company-intro" aria-labelledby="company-title"><Container>
        <div className="company-heading"><div><Eyebrow>Grow-X Co. · Pessoas, produtos e operações</Eyebrow><h1 id="company-title">Tecnologia que começa<br />no <span>seu contexto.</span></h1></div><div className="company-statement"><p>Uma empresa. Três núcleos.<br />Do campo à indústria, ao seu espaço de cultivo.</p><a href="#portais" className="company-down">Encontre o seu caminho <ArrowDown size={17} aria-hidden="true" /></a></div></div>
        <div className="sector-panorama" id="portais">{sectors.map(sector => <article key={sector.id} className="sector-entry"><a href={'#' + sector.id} className="sector-scene-link" aria-label={'Conhecer o núcleo ' + sector.name}><img src={sector.image} srcSet={sector.mobile ? `${sector.mobile} 480w, ${sector.image} 1200w` : undefined} sizes="(min-width: 900px) 33vw, 100vw" width="1200" height="800" alt={sector.alt} fetchPriority={sector.number === '01' ? 'high' : undefined} /><div className="sector-image-label"><span>{sector.number} / Núcleo Grow-X</span><h2>{sector.name}</h2><span className="sector-view">Conhecer o núcleo <ArrowUpRight size={18} aria-hidden="true" /></span></div></a><div className="sector-entry-footer"><span>{sector.product}</span><SectorLink sector={sector} /></div></article>)}</div>
        <p className="acervo-note">Cenas ilustrativas do acervo da marca. A cena Indoor foi gerada por IA; interfaces apresentadas usam dados de demonstração.</p>
      </Container></section>

      <section className="company-purpose" aria-labelledby="purpose-title"><Container><div className="purpose-grid"><Eyebrow>A empresa por trás dos núcleos</Eyebrow><div><h2 id="purpose-title">Contextos diferentes.<br />A mesma atenção ao projeto.</h2><p>A Grow-X Co. reúne software, equipamentos e conhecimento de domínio para conversar sobre o trabalho de quem produz, opera ou cultiva. Cada frente tem sua jornada, sua proposta e seus limites de validação.</p><p className="purpose-boundary">A integração estratégica das frentes não significa conexão técnica automática entre produtos. Integrações são avaliadas por projeto.</p><Link to="/sobre/historia" className="company-text-link">Conheça a Grow-X Co. <ArrowUpRight size={18} aria-hidden="true" /></Link></div></div></Container></section>

      {sectors.map(sector => <section key={sector.id} id={sector.id} className="sector-story" aria-labelledby={sector.id + '-title'}><Container><div className="story-heading"><Eyebrow>{sector.number} / {sector.name}</Eyebrow><span>{sector.product}</span></div><div className="story-grid"><div className="story-copy"><h2 id={sector.id + '-title'}>{sector.headline}</h2><p>{sector.intro}</p><SectorLink sector={sector} className="btn-primary" />{sector.id === 'indoor' && <Link to="/produtos/modulo-sem-fio" className="company-text-link">Conhecer o Módulo Grow-X <ArrowUpRight size={18} aria-hidden="true" /></Link>}</div><figure className="story-context"><img src={sector.image} srcSet={sector.mobile ? `${sector.mobile} 480w, ${sector.image} 1200w` : undefined} sizes="(min-width: 900px) 58vw, 100vw" alt={sector.alt} width="1200" height={sector.id === 'agricultura' ? 675 : 800} loading="lazy" /><figcaption>{sector.id === 'indoor' ? 'Cena ilustrativa gerada por IA; interface real com dados de demonstração.' : 'Cena ilustrativa do acervo editorial da marca.'}</figcaption></figure></div><div className="story-product"><figure><img src={sector.screen} srcSet={sector.screenMobile ? `${sector.screenMobile} 800w, ${sector.screen} 1600w` : undefined} sizes="(min-width: 900px) 52vw, 100vw" alt={sector.screenAlt} loading="lazy" width={sector.id === 'agricultura' ? 1568 : sector.id === 'industria' ? 1440 : 1600} height={sector.id === 'agricultura' ? 734 : sector.id === 'industria' ? 675 : 900} /><figcaption>{sector.id === 'indoor' ? 'Render conceitual oficial. A composição física final é confirmada na proposta.' : 'Tela demonstrada do produto, com dados de demonstração. Recursos sujeitos ao escopo contratado.'}</figcaption></figure><div><h3>{sector.proof}</h3><p>{sector.detail}</p>{sector.href && <p className="story-destination">Esta jornada continua no Supply-X.</p>}</div></div></Container></section>)}

      <section id="supply-x" className="company-conversation"><Container><Eyebrow>Uma conversa para o seu contexto</Eyebrow><h2>Qual é o seu próximo projeto?</h2><div className="conversation-grid"><div><p>Apresente o cenário, as pessoas e o que você precisa organizar. O núcleo certo começa por essa conversa.</p><Link to="/contato" className="btn-primary">Conversar com a Grow-X <ArrowUpRight size={18} aria-hidden="true" /></Link></div><div><h3>Construir em parceria</h3><p>Para integradores, consultorias, lojas e organizações: escopo, responsabilidades e suporte são definidos em conjunto.</p><Link to="/parceiros" className="company-text-link">Conhecer as parcerias <ArrowUpRight size={18} aria-hidden="true" /></Link></div></div></Container></section>
    </div><GreenVeilSection />
  </>;
}
