import { SEO } from '@/components/visual';
import { PageHero } from '@/components/sections';
import { Journey, JourneyCards } from '@/components/sections/MarketingJourney';
import GreenVeilSection from '@/components/sections/GreenVeilSection';

export default function HomePage() {
  return <><SEO title="GXP, Módulo Grow-X e parceiros" description="Organize seus registros no GXP, conheça o módulo de seis saídas AC e converse sobre seu projeto. Supply-X conecta as jornadas de indústria e produtor." path="/"/>
    <PageHero eyebrow="Grow-X · GXP + Módulo" title={<>Seu espaço. Seus registros. <span className="text-emerald-glow">Sua história.</span></>} intro="O GXP reúne Jardim, Diário e contexto dos equipamentos. O Módulo Grow-X é avaliado conforme as necessidades e a compatibilidade do seu projeto." primaryCta={{label:'Conhecer o GXP',href:'/solucoes/growx-app'}} secondaryCta={{label:'Conhecer o módulo',href:'/produtos/modulo-sem-fio'}} imageFit="contain" image="/assets/gxp-context.webp" imageAlt="Cena ilustrativa gerada por IA: pessoa consulta o GXP em seu espaço de cultivo" status="Pré-venda do módulo fechada" badge={<p className="text-sm text-muted-foreground">Cena ilustrativa gerada por IA; interface real com dados de demonstração.</p>}/>
    <Journey id="portais" eyebrow="Escolha seu próximo passo" title="Uma experiência que começa no seu contexto."><JourneyCards items={[{title:'Registrar e consultar',text:'Conheça o Jardim, o Diário e as telas demonstradas do GXP antes de escolher seu acesso.',to:'/solucoes/growx-app',label:'Explorar o GXP'},{title:'Avaliar equipamentos',text:'Seis saídas AC, DHT22 e sensores compatíveis. Composição, instalação e condições são confirmadas na proposta.',to:'/produtos/modulo-sem-fio',label:'Avaliar o módulo'},{title:'Levar à sua loja',text:'Para growshops e parceiros: composição da oferta, demonstração, responsabilidades e suporte definidos no projeto.',to:'/parceiros',label:'Conhecer a parceria'}]}/></Journey>
    <Journey id="supply-x" eyebrow="Indústria e campo" title="Sua operação é industrial ou rural?" intro="Supply-X organiza duas jornadas: SPI para indústria e SPP para produtores. Integrações são avaliadas e contratadas por projeto."><JourneyCards items={[{title:'SPI · Indústria',text:'Organize remessas, qualidade, armazenagem e responsáveis conforme o escopo de sua operação.',href:'https://www.supplyx.com.br/spi',label:'Conhecer o SPI'},{title:'SPP · Produtores',text:'Histórico de áreas, atividades e documentos para agricultura familiar, orgânicos e acompanhamento técnico.',href:'https://www.supplyx.com.br/spp',label:'Conhecer o SPP'},{title:'A Grow-X Co.',text:'Conheça a história, a equipe e os caminhos institucionais da empresa.',to:'/sobre/historia',label:'Conhecer a Grow-X'}]}/></Journey>
    <GreenVeilSection/>
  </>;
}
