import { SEO } from '@/components/visual';
import { PageHero, SpecsTable } from '@/components/sections';
import { Journey, JourneyCards } from '@/components/sections/MarketingJourney';

export default function ModuloSemFioPage() {
 return <><SEO title="Módulo Grow-X · seis saídas AC e compatibilidade" description="Conheça o módulo documentado com seis saídas AC, DHT22 e sensores compatíveis. Composição e instalação são avaliadas por projeto; pré-venda fechada." path="/produtos/modulo-sem-fio"/>
 <PageHero eyebrow="Módulo Grow-X" title={<>O módulo no <span className="text-emerald-glow">seu projeto.</span></>} intro="Um controlador para integrar equipamentos compatíveis ao seu contexto. Seis saídas AC estão documentadas; a composição final do kit e os comandos físicos continuam em validação." primaryCta={{label:'Avaliar compatibilidade',href:'/contato?produto=modulo'}} secondaryCta={{label:'Ver situação da pré-venda',href:'/prevenda'}} imageFit="contain" image="/assets/module-render.webp" imageAlt="Render conceitual do Módulo Grow-X" status="Pré-venda fechada" badge={<p className="text-sm text-muted-foreground">Render oficial conceitual. Varejo: referência de R$ 5.000 por unidade; preço e condições finais na proposta. Esta referência não abre uma oferta de compra.</p>}/>
 <Journey id="como-funciona" eyebrow="Medir, decidir, atuar" title="Leitura de sensor e comando são etapas diferentes." intro="Uma tela de demonstração apresenta informações; ela não comprova acionamento de equipamentos em produção."><JourneyCards items={[{title:'Medir o ambiente',text:'DHT22 para temperatura e umidade do ar; outros sensores precisam ter compatibilidade confirmada.'},{title:'Consultar no GXP',text:'Cadastro, contexto do equipamento e informações disponíveis no app. A interface demonstrada utiliza dados de demonstração.'},{title:'Avaliar a atuação',text:'Seis saídas AC documentadas. Carga, tensão, corrente, instalação e recursos de controle precisam ser validados no projeto.'}]}/></Journey>
 <SpecsTable eyebrow="Base documentada" title="O que sabemos e o que precisa ser confirmado." specs={{'Saídas documentadas':'6 saídas AC','Sensor de referência':'DHT22 · temperatura e umidade do ar','Outros sensores':'Somente modelos compatíveis, definidos na proposta','Kit e acessórios':'Composição final em validação','Instalação elétrica':'Tensão, corrente e carga máxima a confirmar antes da contratação','Comandos físicos':'Em validação; demonstração web não comprova atuação em produção','Situação comercial':'Pré-venda fechada; referência de varejo R$ 5.000/unidade'}}/>
 <Journey eyebrow="Antes da contratação" title="Da necessidade à proposta."><JourneyCards items={[{title:'Conte seu cenário',text:'Informe os equipamentos que deseja avaliar. A conversa inicial pode começar com nome e contato.',to:'/contato?produto=modulo',label:'Avaliar compatibilidade'},{title:'Conheça o GXP',text:'Veja o percurso de Jardim, Diário e informações do módulo. O acesso ao app é uma escolha separada.',to:'/solucoes/growx-app',label:'Explorar o GXP'},{title:'Growshop ou parceiro?',text:'Composição da oferta, suporte e responsabilidades são definidos na proposta.',to:'/parceiros',label:'Conhecer parceria'}]}/></Journey></>;
}
