import InstitutionalVideo from '@/components/sections/InstitutionalVideo';
import { SEO } from '@/components/visual';
import { PageHero } from '@/components/sections';
import { Journey, JourneyCards } from '@/components/sections/MarketingJourney';
export default function SPIPage() {
 return <><SEO title="SPI · operação industrial" description="Remessas, qualidade, armazenagem e responsabilidades conforme o escopo da sua operação. Confira os percursos e converse sobre o projeto no Supply-X." path="/solucoes/spi"/>
 <PageHero eyebrow="Grow-X · Supply-X" title="SPI · operação industrial" intro="Remessas, qualidade, armazenagem e responsabilidades conforme o escopo da sua operação. Confira os percursos e converse sobre o projeto no Supply-X." primaryCta={{label:'Conhecer no Supply-X',href:'https://www.supplyx.com.br/spi',external:true}} secondaryCta={{label:'Conversar com o time',href:'/contato?produto=spi'}} status="Integração contratada por projeto"/>
 <InstitutionalVideo videoId="NrIKQpXUyO8" sectionId="video-spi" copy={{PT:{eyebrow:'Apresentação SPI',title:'Conheça o SPI.',description:'Apresentação existente. Escopo e integrações dependem da proposta confirmada.',videoTitle:'Apresentação SPI'},EN:{eyebrow:'SPI presentation',title:'Meet SPI.',description:'Existing presentation. Scope and integrations depend on the confirmed proposal.',videoTitle:'SPI presentation'}}}/>
 <Journey eyebrow="Próximo passo" title="Conheça o percurso que corresponde à sua necessidade."><JourneyCards items={[{title:'SPI · Indústria',text:'Pequenas, médias e grandes operações: entenda o que precisa organizar antes de definir a implantação.',href:'https://www.supplyx.com.br/spi',label:'Explorar o SPI'},{title:'SPP · Produtores',text:'Agricultura familiar, orgânicos e cooperativas têm percursos distintos. O SPP pode ser avaliado de forma independente do SPI.',href:'https://www.supplyx.com.br/spp',label:'Explorar o SPP'},{title:'Escopo confirmado',text:'Integrações, permissões, conectividade e recursos disponíveis precisam ser confirmados na demonstração e na proposta.',to:'/contato?produto=spi',label:'Conversar sobre o projeto'}]}/></Journey></>;
}
