/* global Request */
import test from 'node:test';
import assert from 'node:assert/strict';
import process from 'node:process';
import fs from 'node:fs';
import {AGENDA_HOST,AGENDA_HEADERS,parseHost,allowedAgendaHosts,hostRoute} from '../../lib/agenda-host-policy.js';
import {requireAgendaHost,requireSameOrigin} from '../../api/_lib/growx-agenda-http.js';
import middleware from '../../middleware.js';
import sessionHandler from '../../api/socios/session.js';
import agendaHandler from '../../api/socios/agenda.js';
const preview={VERCEL_ENV:'preview',VERCEL_GIT_COMMIT_REF:'feat/partners-agenda',VERCEL_URL:'growx-exact.vercel.app',VERCEL_BRANCH_URL:'growx-branch.vercel.app'};
const route=(path,method='GET',host=AGENDA_HOST,env={})=>hostRoute({host,path,method},env);
test('host parser rejects ambiguous and forwarded authorities',()=>{for(const h of [null,undefined,[],AGENDA_HOST+':443',AGENDA_HOST+'.',AGENDA_HOST+',www.growx.com.br','evil@'+AGENDA_HOST,' '+AGENDA_HOST,AGENDA_HOST+'/'])assert.equal(parseHost(h),null);assert.equal(parseHost('AGENDA.GROWX.COM.BR'),AGENDA_HOST)});
test('only production agenda and exact explicitly enabled branch preview hosts allowed',()=>{assert.deepEqual([...allowedAgendaHosts({})],[AGENDA_HOST]);assert.equal(allowedAgendaHosts(preview).size,3);for(const env of [{...preview,VERCEL_ENV:'production'},{...preview,VERCEL_GIT_COMMIT_REF:'main'},{...preview,VERCEL_ENV:'development'}])assert.equal(allowedAgendaHosts(env).size,1);for(const h of ['www.growx.com.br','growx.com.br','growx-flame.vercel.app','other.vercel.app'])assert.equal(allowedAgendaHosts(preview).has(h),false);assert.equal(route('/', 'GET',preview.VERCEL_URL,preview).action,'rewrite')});
test('app host serves only agenda documents, APIs and isolated build assets',()=>{for(const p of ['/','/socios/agenda','/socios/agenda/','/socios-agenda.html'])assert.equal(route(p).action,'rewrite');for(const p of ['/api/socios/session','/api/socios/agenda']){assert.equal(route(p).action,'next');assert.equal(route(p,'POST').action,'next')}for(const p of ['/favicon.svg','/agenda-assets/socios-agenda-Baeo-ZrH.js','/agenda-assets/geist-latin-wght-normal-BgDaEnEv.woff2'])assert.equal(route(p).action,'next');for(const p of ['/index.html','/prevenda','/prevenda.html','/modulo','/financeiro','/contratos/prevenda-v3-2026-08-08.html','/api/orders','/api/cron/reconcile','/assets/main-B7W2Uabk.js','/manifest.webmanifest','/robots.txt','/api/socios/session/','/api/socios/agenda.js','/agenda-assets/test.html','/agenda-assets/test-12345678.js.map','/agenda-assets/../index.html','/agenda-assets/%2e%2e/index.html','/%2561pi/orders','//prevenda','/prevenda;','/foo\\bar'])assert.equal(route(p).action,'deny',p);for(const method of ['PUT','DELETE','OPTIONS','TRACE'])assert.equal(route('/api/socios/agenda',method).action,'deny')});
test('marketing requests preserve existing routes but cannot expose agenda API or assets',()=>{for(const host of ['www.growx.com.br','growx.com.br','growx-flame.vercel.app']){for(const path of ['/','/prevenda','/modulo','/api/orders','/assets/main-B7W2Uabk.js'])assert.equal(route(path,'GET',host).action,'next');assert.equal(route('/api/socios/agenda','GET',host).action,'deny');assert.equal(route('/agenda-assets/app-12345678.js','GET',host).action,'deny');assert.equal(route('/socios/agenda','GET',host).action,'redirect')}});
test('API independently rejects wrong Host/Origin, including same-site marketing and preview',()=>{for(const host of ['www.growx.com.br','growx.com.br','other.vercel.app',AGENDA_HOST+':443',undefined])assert.throws(()=>requireAgendaHost({headers:{host,'x-forwarded-host':AGENDA_HOST,'x-original-host':AGENDA_HOST}}),e=>e.status===403);for(const origin of ['null','https://www.growx.com.br','https://growx.com.br','https://growx-exact.vercel.app','http://'+AGENDA_HOST])assert.throws(()=>requireAgendaHost({headers:{host:AGENDA_HOST,origin}},preview),e=>e.status===403);assert.equal(requireAgendaHost({headers:{host:AGENDA_HOST}}),AGENDA_HOST);assert.equal(requireAgendaHost({headers:{host:preview.VERCEL_URL,origin:'https://'+preview.VERCEL_URL}},preview),preview.VERCEL_URL);assert.throws(()=>requireSameOrigin({headers:{host:AGENDA_HOST,'content-type':'application/json'}}),e=>e.status===403)});
test('rejected API hosts fail before configuration/DB and disclose no agenda payload',async()=>{for(const handler of [sessionHandler,agendaHandler])for(const method of ['GET','POST']){let status,body;const headers={};const res={setHeader(k,v){headers[k]=v},status(v){status=v;return this},json(v){body=v;return this}};await handler({method,headers:{host:'www.growx.com.br',origin:'https://www.growx.com.br',cookie:'__Host-growx_agenda=synthetic-invalid'}},res);assert.equal(status,403);assert.equal(body.items,undefined);assert.equal(headers['Access-Control-Allow-Origin'],undefined);assert.equal(headers['Set-Cookie'],undefined)}});
test('middleware returns fixed agenda rewrite or inert 404 before filesystem',()=>{for(const [path,expected] of [['/',200],['/index.html',404],['/prevenda.html',404],['/api/orders',404]]){const res=middleware(new Request('https://'+AGENDA_HOST+path,{headers:{host:AGENDA_HOST}}));assert.equal(res.status,expected);assert.equal(res.headers.get('content-security-policy'),AGENDA_HEADERS['Content-Security-Policy']);if(expected===200)assert.equal(res.headers.get('x-middleware-rewrite'),'https://'+AGENDA_HOST+'/socios-agenda.html');assert.equal(res.headers.get('set-cookie'),null)}assert.equal(middleware(new Request('https://'+AGENDA_HOST+'/',{headers:{host:'www.growx.com.br'}})).status,404)});
test('middleware exact preview host has same route restriction and headers',()=>{const saved={...process.env};Object.assign(process.env,preview);try{const response=middleware(new Request('https://'+preview.VERCEL_URL+'/prevenda.html',{headers:{host:preview.VERCEL_URL}}));assert.equal(response.status,404);assert.equal(response.headers.get('cross-origin-resource-policy'),'same-origin')}finally{for(const key of Object.keys(preview)){if(saved[key]===undefined)delete process.env[key];else process.env[key]=saved[key]}}});
test('marketing fallback excludes agenda asset namespace and production agenda host',()=>{const v=JSON.parse(fs.readFileSync('vercel.json','utf8'));for(const r of v.rewrites.filter(r=>['/','/prevenda.html'].includes(r.destination)))assert(r.missing.some(c=>c.type==='host'&&c.value===AGENDA_HOST));assert(v.rewrites.find(r=>r.destination==='/').source.includes('agenda-assets/'));const config=fs.readFileSync('vite.agenda.config.js','utf8');assert.match(config,/publicDir:false/);assert.match(config,/assetsDir:'agenda-assets'/);assert.doesNotMatch(fs.readFileSync('vite.config.js','utf8'),/socios-agenda/)});

test('encoded private document/API aliases never pass the marketing gate',()=>{for(const path of ['/socios%2dagenda.html','/%73ocios-agenda.html','/%61pi/socios/session','/socios%252dagenda.html','/%2573ocios-agenda.html','/socios/agenda;anything','/agenda-assets%2fapp-12345678.js','/socios%5cagenda','/socios%2fagenda','/foo/..%2fsocios-agenda.html','/foo/..%252fsocios-agenda.html','/%73ocios-agenda.html?configurar=senha','/%zz'])assert.equal(route(path,'GET','www.growx.com.br').action,'deny',path)});
