import test from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';import {createHash} from 'node:crypto';
import {createAgendaAuthService,createPasswordHash,parseAccountsConfig,COOKIE} from '../../api/_lib/growx-agenda-auth.js';
import {requireSameOrigin,requestBody,allowedOrigins,safeError} from '../../api/_lib/growx-agenda-http.js';
const password='test-only-not-a-real-credential';
const hash=await createPasswordHash(password,'11111111111111111111111111111111');
const accountConfig={fernando:{email:'fernando@example.invalid',hash},jefferson:{email:'jefferson@example.invalid',hash:await createPasswordHash(password+'-jeff','22222222222222222222222222222222')},julio:{email:'julio@example.invalid',hash:await createPasswordHash(password+'-julio','33333333333333333333333333333333')}};
const accountsJson=JSON.stringify(accountConfig);
async function fixture(){const db=new PGlite();await db.exec("CREATE SCHEMA growx_agenda; CREATE TABLE growx_agenda.sessions(token_hash text primary key,person text,password_version text,created_at timestamptz default now(),expires_at timestamptz,revoked_at timestamptz); CREATE TABLE growx_agenda.login_attempts(key_hash text primary key,attempts int,resets_at timestamptz);");const auth=createAgendaAuthService({pool:db,accountsJson});return {db,auth}}
function request(extra={}){return {headers:{'x-vercel-forwarded-for':'192.0.2.1',...extra}}}
const body={email:'fernando@example.invalid',password};
test('hash uses PBKDF2 SHA256 with 600000 iterations, salt and digest',()=>{assert.match(hash,/^pbkdf2-sha256\$600000\$[a-f0-9]{32}\$[a-f0-9]{64}$/);assert(!hash.includes(password));assert.throws(()=>createAgendaAuthService({pool:{},accountsJson:'invalid'}));});
test('login issues protected cookie and stores only token hash',async()=>{const {db,auth}=await fixture();try{const result=await auth.login(request(),body);assert.match(result.cookie,/; Path=\/; Secure; HttpOnly; SameSite=Strict; Max-Age=28800$/);const raw=result.cookie.split(';')[0].split('=')[1];const rows=await db.query('SELECT * FROM growx_agenda.sessions');assert.equal(rows.rows[0].token_hash,createHash('sha256').update(raw).digest('hex'));assert.notEqual(rows.rows[0].token_hash,raw);assert.equal(result.user.actor,'Fernando <fernando@example.invalid>');assert(!JSON.stringify(result.user).includes(raw));const user=await auth.authenticate(request({cookie:result.cookie.split(';')[0]}));assert.equal(user.person,'fernando');}finally{await db.close()}});
test('missing, malformed, duplicated and invented session tokens fail closed',async()=>{const {db,auth}=await fixture();try{assert.equal(await auth.authenticate(request()),null);assert.equal(await auth.authenticate(request({cookie:COOKIE+'=bad'})),null);assert.equal(await auth.authenticate(request({cookie:COOKIE+'='+'a'.repeat(43)+'; '+COOKIE+'='+'a'.repeat(43)})),null);assert.equal(await auth.authenticate(request({cookie:COOKIE+'='+'a'.repeat(43)})),null)}finally{await db.close()}});
test('logout revokes session and expires cookie',async()=>{const {db,auth}=await fixture();try{const result=await auth.login(request(),body);const req=request({cookie:result.cookie.split(';')[0]});assert.match(await auth.logout(req),/Max-Age=0$/);assert.equal(await auth.authenticate(req),null)}finally{await db.close()}});
test('expired session and changed password hash invalidate access',async()=>{const {db,auth}=await fixture();try{const result=await auth.login(request(),body);const req=request({cookie:result.cookie.split(';')[0]});const changed=createAgendaAuthService({pool:db,accountsJson:JSON.stringify({...accountConfig,fernando:{...accountConfig.fernando,hash:await createPasswordHash(password+'-rotated','44444444444444444444444444444444')}})});assert.equal(await changed.authenticate(req),null);await db.query("UPDATE growx_agenda.sessions SET expires_at=now()-interval '1 minute'");assert.equal(await auth.authenticate(req),null)}finally{await db.close()}});
test('unknown email and invalid IP cannot create a session',async()=>{const {db,auth}=await fixture();try{await assert.rejects(auth.login(request(),{...body,email:'unknown@example.invalid'}),e=>e.status===401);await assert.rejects(auth.login({headers:{}},body),e=>e.status===403);await assert.rejects(auth.login(request({'x-vercel-forwarded-for':'invalid'}),body),e=>e.status===403);assert.equal((await db.query('SELECT count(*)::int n FROM growx_agenda.sessions')).rows[0].n,0)}finally{await db.close()}});
test('bad passwords reserve persistent attempts and lock out at the limit',async()=>{const {db,auth}=await fixture();try{await db.query("INSERT INTO growx_agenda.login_attempts VALUES ($1,9,now()+interval '15 minutes')",[createHash('sha256').update('growx-agenda:192.0.2.1').digest('hex')]);await assert.rejects(auth.login(request(),{...body,password:'wrong'}),e=>e.status===401);await assert.rejects(auth.login(request(),body),e=>e.status===429);assert.equal((await db.query('SELECT count(*)::int n FROM growx_agenda.sessions')).rows[0].n,0);await db.query("UPDATE growx_agenda.login_attempts SET resets_at=now()-interval '1 second'");assert((await auth.login(request(),body)).cookie)}finally{await db.close()}});
test('CSRF requires exact configured origin and JSON',()=>{const origins=allowedOrigins({VERCEL_URL:'preview.vercel.app'});for(const origin of [undefined,'https://attacker.example','https://www.growx.com.br.attacker.example'])assert.throws(()=>requireSameOrigin({headers:{origin,'content-type':'application/json'}},origins));assert.throws(()=>requireSameOrigin({headers:{origin:'https://www.growx.com.br','content-type':'text/plain'}},origins));assert.doesNotThrow(()=>requireSameOrigin({headers:{origin:'https://www.growx.com.br','content-type':'application/json'}},origins));assert.doesNotThrow(()=>requireSameOrigin({headers:{origin:'https://preview.vercel.app','content-type':'application/json'}},origins));});
test('request validation rejects invalid JSON, arrays and oversize payloads',()=>{for(const body of ['{',[],null])assert.throws(()=>requestBody({headers:{},body}));assert.throws(()=>requestBody({headers:{'content-length':'1300000'},body:{action:'login'}}));assert.deepEqual(requestBody({headers:{},body:'{"action":"logout"}'}),{action:'logout'});});

test('individual credentials cannot select or impersonate another partner',async()=>{const {db,auth}=await fixture();try{await assert.rejects(auth.login(request(),{email:'julio@example.invalid',password}),e=>e.status===401);const result=await auth.login(request(),{...body,person:'julio'});assert.equal(result.user.person,'fernando');assert.equal(result.user.email,'fernando@example.invalid');const julio=await auth.login(request(),{email:' JULIO@EXAMPLE.INVALID ',password:password+'-julio'});assert.equal(julio.user.person,'julio')}finally{await db.close()}});
test('rotating one account leaves other accounts sessions intact',async()=>{const {db,auth}=await fixture();try{const result=await auth.login(request(),{email:'julio@example.invalid',password:password+'-julio'});const changed=createAgendaAuthService({pool:db,accountsJson:JSON.stringify({...accountConfig,fernando:{...accountConfig.fernando,hash:await createPasswordHash(password+'-rotated','44444444444444444444444444444444')}})});assert.equal((await changed.authenticate(request({cookie:result.cookie.split(';')[0]}))).person,'julio')}finally{await db.close()}});
test('account configuration rejects missing, extra, duplicated and malformed identities',()=>{for(const config of [{},{...accountConfig,extra:accountConfig.fernando},{...accountConfig,julio:{...accountConfig.julio,email:accountConfig.fernando.email}},{...accountConfig,julio:{...accountConfig.julio,hash:hash}},{...accountConfig,julio:{...accountConfig.julio,email:'not-an-email'}}])assert.throws(()=>parseAccountsConfig(JSON.stringify(config)));assert.equal(Object.keys(parseAccountsConfig(accountsJson)).length,3)});

test('service diagnostics expose categories but never raw credential-bearing errors',()=>{for(const code of ['SELF_SIGNED_CERT_IN_CHAIN','28P01','ERR_INVALID_URL','42P01','42501','ENOTFOUND','unknown','toString','__proto__']){let output;const response={status(s){assert.equal(s,503);return this},json(value){output=value;return value}};safeError(Object.assign(new Error('postgres://secret:credential@private-host SQL query and input'),{code}),response);assert.equal(typeof output.incident,'string');assert(!JSON.stringify(output).includes('credential@'));assert(!JSON.stringify(output).includes('private-host'));assert(!JSON.stringify(output).includes('SQL query'));} });
