import {useState} from 'react';
import logo from '@/assets/logo-growx-oficial.png';
import {makeDatabaseSetup} from './database-setup.js';
export default function DatabaseSetup(){
 const [result,setResult]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 function prepare(event){event.preventDefault();const values=new FormData(event.currentTarget);setError('');setNotice('');try{setResult(makeDatabaseSetup(String(values.get('host')||'').trim(),String(values.get('project')||'').trim()))}catch(e){setError(e.message)}}
 async function copy(value,message){try{await navigator.clipboard.writeText(value);setNotice(message)}catch{setError('Não foi possível copiar. Tente novamente pelo botão.')}}
 return <main className="agenda-gate"><section className="agenda-login agenda-setup"><img src={logo} alt="Grow-X"/><h1>Conectar o banco da agenda</h1><p>Esta preparação gera uma credencial técnica separada, somente neste navegador. Não altera o banco ou o Vercel por conta própria.</p>{!result?<form onSubmit={prepare} autoComplete="off"><label>Host do transaction pooler<input name="host" required autoComplete="off" spellCheck="false" placeholder="Copiado do painel oficial do Supabase"/></label><label>Referência do projeto<input name="project" required autoComplete="off" spellCheck="false" maxLength={20}/></label><button className="button primary">Preparar conexão restrita</button></form>:<><ol className="help-list"><li>No editor SQL oficial do projeto autorizado, substitua o texto inteiro pelo comando copiado abaixo. Execute Run, confira o sucesso e apague a consulta. Não salve o comando como snippet.</li><li>Copie a conexão e cole no campo Secret AGENDA_DATABASE_URL do projeto growx no Vercel. Salve.</li></ol><button className="button primary" onClick={()=>copy(result.sql,'Comando copiado. Cole e execute somente no editor SQL do projeto autorizado; depois apague a consulta.')}>1. Copiar comando para o Supabase</button><button className="button primary" onClick={()=>copy(result.url,'Conexão copiada. Cole somente em AGENDA_DATABASE_URL, tipo Secret, no Vercel.')}>2. Copiar conexão para o Vercel</button><button className="button" onClick={()=>{setResult(null);setNotice('Credencial removida desta tela.');setError('')}}>Limpar esta tela</button></>}{error&&<p className="agenda-gate-error" role="alert">{error}</p>}{notice&&<p className="agenda-gate-note" role="status">{notice}</p>}<p className="agenda-gate-note">O comando atua somente no usuário growx_agenda_runtime já criado. Não compartilhe o comando ou a conexão pelo chat. Depois de configurar os dois serviços, limpe esta tela. Não gere novamente se já estiver conectado, pois isso exigiria atualizar os dois lados.</p></section></main>;
}
